<?php

namespace App\Domain\Entity;

use Symfony\Component\Uid\Uuid;

/**
 * Add an ID to objects
 */
trait IdTrait
{
    /** Id generated by the ORM */
    protected $id;

    /** @return Uuid */
    public function getId(): Uuid
    {
        return $this->id;
    }

    /** @return self */
    public function setId(Uuid $id): self
    {
        $this->id = $id;

        return $this;
    }
}
